import type { Metadata } from "next";

import "./globals.css";
import { ReduxProvider } from "@/redux/provider/ReduxProvider";

export const metadata: Metadata = {
  title: "ESBU_M94",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
